In [65]:
import numpy as np

matrix1 = np.mat("1 2 3;4 5 6;7 8 9")
print("原矩阵：")
print(matrix1)
print(type(matrix1))

a = np.arange(8)
a = a.reshape(4,2)
print("原数组：")
print(a)
print(type(a))

原矩阵：
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>
原数组：
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
<class 'numpy.ndarray'>


In [19]:
print("矩阵最大值是：")
print(matrix1.max())

print("矩阵最小值是：")
print(matrix1.min())

矩阵最大值是：
9
矩阵最小值是：
1


In [21]:
print("矩阵平均值是：")
print(matrix1.mean())

print("矩阵的方差是：")
print(matrix1.var())

print("矩阵的标准差是：")
print(matrix1.std())

矩阵平均值是：
5.0
矩阵的方差是：
6.666666666666667
矩阵的标准差是：
2.581988897471611


In [23]:
print("数组整形：")

数组整形：


In [25]:
print("矩阵转置：")
print(matrix1.T)

矩阵转置：
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [27]:
print("扁平化矩阵：")
print(matrix1.ravel())
print(matrix1.flatten())

扁平化矩阵：
[[1 2 3 4 5 6 7 8 9]]
[[1 2 3 4 5 6 7 8 9]]


In [34]:
print("找矩阵的秩：")
print(np.linalg.matrix_rank(matrix1))

找矩阵的秩：
2


In [41]:
print("计算矩阵行列式的值：")
print(np.linalg.det(matrix1))

计算矩阵行列式的值：
6.66133814775094e-16
-2.0000000000000004


In [45]:
print("获取矩阵对角元素：")
print(np.diag(matrix1))
print(np.diagonal(matrix1))

获取矩阵对角元素：
[1 5 9]
[1 5 9]


In [48]:
print("计算矩阵的迹：")
print(matrix1.trace())

计算矩阵的迹：
[[15]]


In [51]:
print("找特征值和向量")
print("矩阵的特征值")
print(np.linalg.eigvals(matrix1))
print("返回包含特征值和对应的特征向量的元组")
print(np.linalg.eig(matrix1))

找特征值和向量
矩阵的特征值
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
返回包含特征值和对应的特征向量的元组
(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), matrix([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))


In [54]:
matrix2 = np.mat("1 3 5;2 4 6;10 12 7")
print("matrix2：")
print(matrix2)

print("计算点积：")
print(np.dot(matrix1,matrix2))

matrix2：
[[ 1  3  5]
 [ 2  4  6]
 [10 12  7]]
计算点积：
[[ 35  47  38]
 [ 74 104  92]
 [113 161 146]]


In [60]:
print(matrix1)
print(matrix2)
print("计算矩阵的加法：")
print(np.add(matrix1,matrix2))
print("计算矩阵的减法：")
print(np.subtract(matrix1,matrix2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  3  5]
 [ 2  4  6]
 [10 12  7]]
计算矩阵的加法：
[[ 2  5  8]
 [ 6  9 12]
 [17 20 16]]
计算矩阵的减法：
[[ 0 -1 -2]
 [ 2  1  0]
 [-3 -4  2]]


In [64]:
print("计算矩阵的乘法：")
print(np.multiply(matrix1,matrix2))
print("计算矩阵的求逆：")
print(matrix1.I)

计算矩阵的乘法：
[[ 1  6 15]
 [ 8 20 36]
 [70 96 63]]
计算矩阵的求逆：
[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
